debug: true
cache: false
display_errors: false

db:
  default:
    client: mongodb://mongo:27017
    database: legalevents

rollbar: false

email:
  From: test@example.com
  FromName: Test
  Mailer: mail

queuer:
  url: http://event-queuer

anchor:
  url: http://anchor

environment_variables:
  MONGO_DB: db.default.client
  MONGO_DB_PREFIX: db.default.prefix
