debug: true
cache: false
display_errors: false

db:
  default:
    client: mongodb://mongo:27017
    database: legalevents

rollbar: false

email:
  From: test@example.com
  FromName: Test
  Mailer: mail

endpoints:
  "lt:/scenarios/*":      "http://legalflow/scenarios/"
  "lt:/processes/*":      "http://legalflow/responses/"
  "lt:/processes/*/done": "http://legalflow/processes/$2/done"

dispatcher:
  url: http://event-dispatcher

environment_variables:
  MONGO_DB: db.default.client
  MONGO_DB_PREFIX: db.default.prefix
